In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
from nn_magnetics.data import IsotropicData

In [11]:
data = IsotropicData(path="../data/isotropic_chi/train")

In [13]:
data

IsotropicData(
	4340000 data points
	6 input features
	6 output features
)

In [14]:
data[0]

(tensor([3.8992e-01, 2.5924e+00, 9.5898e-01, 2.5646e-06, 3.8574e-07, 6.0000e-01],
        dtype=torch.float64),
 tensor([8.4778e-07, 1.3565e-08, 2.2666e-01, 9.9360e-07, 1.6018e-08, 2.4488e-01],
        dtype=torch.float64))

In [15]:
data[1]

(tensor([3.8992e-01, 2.5924e+00, 9.5898e-01, 2.5646e-06, 3.8574e-07, 7.0000e-01],
        dtype=torch.float64),
 tensor([5.4668e-07, 1.4909e-08, 1.5546e-01, 6.0012e-07, 1.6678e-08, 1.6451e-01],
        dtype=torch.float64))