In [1]:
%load_ext autoreload
%autoreload 2

In [117]:
from nn_magnetics.pytorch.corrections import angle_amp_correction
from nn_magnetics.utils import batch_rotation_matrices
import numpy as np

In [118]:
import torch

R = batch_rotation_matrices(torch.tensor([[torch.pi, 0, 0], [0, 0, 0]]))

In [111]:
V = torch.rand((2, 3))

In [112]:
A = 0.5 * torch.ones((3))

In [113]:
A

tensor([0.5000, 0.5000, 0.5000])

In [114]:
V

tensor([[0.9971, 0.6984, 0.5675],
        [0.8352, 0.2056, 0.5932]])

In [115]:
ARV = A*torch.einsum("nij,nj->ni", R, V)

In [116]:
ARV

tensor([[ 0.4985, -0.3492, -0.2838],
        [ 0.4176,  0.1028,  0.2966]])